Export: write custom attribute arrays for non-skinning vgroups
KhronosGroup/glTF-Blender-IO pull request #1515
Opened 2021-12-22 05:51 UTC by canadaduane

I've combined the facemap exports and vertex group exports from @scurest's work last year, and tested that this works on 3.0.0.

I haven't followed all of the changes and improvements since Nov 2020, however, so I'm not sure if this is still the ideal way to do things. There are also a couple of places where a line of code has been commented out (e.g. gltf2_blender_gather_nodes.py has `#vertex_groups = None` in a couple of places). We should probably decide what we want to happen--either remove it, or improve it?

#1232

2021-12-22 08:04 UTC, julienduroure commented
> There are also a couple of places where a line of code has been commented out (e.g. gltf2_blender_gather_nodes.py has #vertex_groups = None in a couple of places). We should probably decide what we want to happen--either remove it, or improve it?

We can't remove it, it will lead to miss cache. 
The solution is to use a custom cache, as I started to implement (based in scurest suggestion) in vtree branch.
This will be nedded also for other requests (see #900 #747 #1245)

2021-12-22 08:07 UTC, julienduroure requested changes

2021-12-22 08:07 UTC, julienduroure commented on addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py
> +                #vertex_groups = None # Not needed if no armature, avoid a cache miss
This can lead to miss cache

2021-12-23 15:00 UTC, canadaduane commented
Ok, cool, so this PR should wait until your work there on custom caches is done? If I understand #1245 is the ticket to watch.

2021-12-23 23:47 UTC, scurest commented
It does not require a custom cache. It will also not cause a cache miss: if there are non-skinning vgroups, this branch _always_ exports them, so since the vgroups are always used, it is correct that they are always part of the cache key. But I don't think it is good that they are always exported. If it's desirable to merge these features into mainline, I think they should be behind an export option, cf https://github.com/KhronosGroup/glTF-Blender-IO/issues/1232#issuecomment-705290610.

2021-12-24 07:57 UTC, julienduroure commented
BTW, some other custom attribute can be exported, as requested by some blender devs. See #1505

Anyway, now that vertex groups are stored on mesh, no more on object, all this code needs to be refactored.

2021-12-24 08:40 UTC, scurest commented
> Anyway, now that vertex groups are stored on mesh, no more on object, all this code needs (probably) to be refactored.

Oh, that's right. `vertex_groups = None` is always unnecessary now, since two instances of the same mesh always have the same vertex groups. It still has to be passed down though since there's no API for getting it off the mesh.

2022-03-30 10:53 UTC, iuriiiurevich commented
> Plus one to the idea of adding this feature to the official exporter (as an export option)!

@julienduroure Are there any plans to do so?
By the way, thanks for your amazing work!

2026-06-20 02:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/glTF-Blender-IO?pullRequest=1515) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/glTF-Blender-IO?pullRequest=1515) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/glTF-Blender-IO?pullRequest=1515) it.</sub>

2026-07-09 16:08 UTC, julienduroure commented
This PR is quite old, CLA is not signed, facemaps is not exists anymore, and the PR has many conflicts
Closing this ticket.
Feel free to open a new ticket or PR if you want

2026-07-09 16:08 UTC, closed without merging